services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      PUID: <UID_of_user_running_app> # e.g. an admin or tech user. Type `id <username>` in a terminal connected as an admin user to retrieve IDs.
      PGID: <GID_of_user_running_app> # e.g. an admin or tech user. Type `id <username>` in a terminal connected as an admin user to retrieve IDs.
      TZ: Europe/Brussels
      UMASK: 022
    volumes:
      - /volume1/docker/sonarr:/config
      - /volume1/data:/data
    ports:
      - 8989:8989/tcp
    security_opt:
      - no-new-privileges:true
    restart: always
  
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      PUID: <UID_of_user_running_app> # e.g. an admin or tech user. Type `id <username>` in a terminal connected as an admin user to retrieve IDs.
      PGID: <GID_of_user_running_app> # e.g. an admin or tech user. Type `id <username>` in a terminal connected as an admin user to retrieve IDs.
      TZ: Europe/Brussels
      UMASK: 022
    volumes:
      - /volume1/docker/lidarr:/config
      - /volume1/data:/data
    ports:
      - 8686:8686/tcp
    security_opt:
      - no-new-privileges:true
    restart: always   
    
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      PUID: <UID_of_user_running_app> # e.g. an admin or tech user. Type `id <username>` in a terminal connected as an admin user to retrieve IDs.
      PGID: <GID_of_user_running_app> # e.g. an admin or tech user. Type `id <username>` in a terminal connected as an admin user to retrieve IDs.
      TZ: Europe/Brussels
      UMASK: 022
    volumes:
      - /volume1/docker/radarr:/config
      - /volume1/data:/data
    ports:
      - 7878:7878/tcp
    security_opt:
      - no-new-privileges:true
    restart: always

  readarr:
    image: linuxserver/readarr:develop
    container_name: readarr
    environment:
      PUID: <UID_of_user_running_app> # e.g. an admin or tech user. Type `id <username>` in a terminal connected as an admin user to retrieve IDs.
      PGID: <GID_of_user_running_app> # e.g. an admin or tech user. Type `id <username>` in a terminal connected as an admin user to retrieve IDs.
      TZ: Europe/Brussels
      UMASK: 022
    volumes:
      - /volume1/docker/readarr:/config
      - /volume1/data/:/data
    ports:
      - 8787:8787/tcp
    security_opt:
      - no-new-privileges:true
    restart: always

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      PUID: <UID_of_user_running_app> # e.g. an admin or tech user. Type `id <username>` in a terminal connected as an admin user to retrieve IDs.
      PGID: <GID_of_user_running_app> # e.g. an admin or tech user. Type `id <username>` in a terminal connected as an admin user to retrieve IDs.
      TZ: Europe/Brussels
      UMASK: 022
    volumes:
      - /volume1/docker/bazarr:/config
      - /volume1/data/:/data
    ports:
      - 6767:6767/tcp
    security_opt:
      - no-new-privileges:true
    restart: always
