services:
  pihole:
    image: pihole/pihole
    container_name: Pi-Hole
    network_mode: host
    security_opt:
      - no-new-privileges:false
    restart: on-failure:5
    volumes:
      - /volume1/docker/pihole/dnsmasq.d:/etc/dnsmasq.d:rw
      - /volume1/docker/pihole/pihole:/etc/pihole:rw
    environment:
      FTLCONF_webserver_api_password: <my_strong_password>
      FTLCONF_webserver_port: 8080
      FTLCONF_dns_listeningMode: all
      TZ: Europe/Brussels
      DNSMASQ_USER: pihole #or root NOT recommended to use root.
      PIHOLE_UID: <UID_of_user_running_app> # e.g. an admin or tech user. Type `id <username>` in a terminal connected as an admin user to retrieve IDs.
      PIHOLE_GID: <GID_of_user_running_app> # e.g. an admin or tech user. Type `id <username>` in a terminal connected as an admin user to retrieve IDs.
    cap_add:
      - SYS_TIME
      - SYS_NICE
